name: Main
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.x
          cache: true
      - name: Run golangci-lint
        # run: |
        #   curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
        #   $(go env GOPATH)/bin/golangci-lint run --timeout=5m -c .golangci.yml
        uses: golangci/golangci-lint-action@v3
        ### golangci-lint will take much time if loading multiple linters in .golangci.yml
        with:
          version: latest
          args: --timeout 5m --verbose
          skip-cache: false
          skip-pkg-cache: false
          skip-build-cache: false
          only-new-issues: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"
      - name: Tidy go module
        run: |
          go mod tidy
          if [[ $(git status --porcelain) ]]; then
            git diff
            echo
            echo "go mod tidy made these changes, please run 'go mod tidy' and include those changes in a commit"
            exit 1
          fi
      - name: Run Go test
        run: go test -v -timeout=30m ./...
      - name: Run Go test -race
        if: github.ref == 'refs/heads/stage' ||  startsWith(github.ref, 'refs/heads/release')
        run: go test -vet=off -timeout=30m -race ./... # note that -race can easily make the crypto stuff 10x slower